channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - seaborn
  - emcee
  - george
  - corner
  - tqdm
  - astropy
  - celerite
  - numba
  - pytables
  - pip
  - pip:
    - ldtk
    - PyTransit
