channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - jupyter
  - ipykernel
  - nbconvert
  - seaborn
  - emcee
  - george
  - corner
  - tqdm
  - astropy
  - celerite
  - numba
  - pytables
  - jax
  - arviz
  - pip
  - pip:
    - ldtk
    - PyTransit
    - tinygp
    - numpyro
    - jaxopt
